---
title: search-field
name: search-field
collection: atoms
notes: |
  ##### Usage : `search-field`
---
<form class="input-group search-field" id="search-field">
  <input type="text" class="form-control" placeholder="Search for...">
  <span class="input-group-btn">
    <button class="btn btn-success" type="button">
      <i class="icon icon-search"></i>
    </button>
    <button class="btn btn-success" type="submit">
      <i class="icon icon-search"></i>
    </button>
  </span>
</form>
