---
title: shadow-separator
name: shadow-separator
collection: atoms
notes: |
  ##### Usage : `shadow-separator`
  Can be also applied to blocks using the classes `.shadow-separator` combined, if needed, with `.shadow-separator-left`, `.shadow-separator-right`, `.shadow-separator-bottom`  or `.shadow-separator-top`. **Warning**, can be only `left + right` or `top + bottom`, not `left + top`, we have only 2 pseudo-element per block...
---
<hr class="shadow-separator">
