---
title: consultation-teaser
name: consultation-teaser
collection: molecules
notes: |
  ##### Usage : `consultation-teaser`
---
<div class="consultation-teaser">
  <h3><a href="#">Consultations préopératoires&nbsp;:</a></h3>
  <p>
    <strong>Rendez-vous</strong> : secrétariat d’anesthésie : 021 977 58 45 (08h30 à 12h00 et de 13h00 à 16h00)
  </p>
  <p>
    <strong>Dr Gérald Seematter</strong><br>
    médecin chef service d’anesthésie
  </p>
  <p>
    <strong>Montreux</strong> : du lundi au vendredi de 13h00 à 15h00<br>
    <strong>Providence</strong> : lundi / mercredi au vendredi de 13h00 à 15h00<br>
    <strong>Samaritain</strong> : du lundi au jeudi de 13h00 à 15h00
  </p>
</div>
