---
title: news-teaser
name: news-teaser
collection: molecules
notes: |
  ##### Usage : `news-teaser`
---
<div class="news-teaser theme-primary">
  <div class="row">
    <div class="col-xs-3 text-right">
      <a href="#" class="btn btn-default">Santé</a>
    </div>
    <div class="col-xs-9">
      <h5><a href="/hrc/post">Lorem ipsum dolor sit amet</a></h5>
      <small class="news-date">
        <strong>26 avril 2016</strong>
      </small>
      <p>
        Respondent extrema primis, media utrisque, omnia omnibus. Non igitur bene. Negabat igitur ullam esse artem, quae ipsa a se proficisceretur; At iam decimum annum in spelunca iacet. Duo Reges: constructio interrete. Honesta oratio, Socratica, Platonis etiam.
      </p>
    </div>
  </div>
</div>
