---
title: news-teaser
name: news-teaser
collection: molecules
notes: |
  ##### Usage : `news-teaser`
  ##### Options :
  - **option** - Type
---
<div class="news-teaser theme-primary">
  <div class="row">
    <div class="col-xs-2 text-right">
      {% include '../atoms/label.html.swig' with {'label': 'Santé'} %}
    </div>
    <div class="col-xs-10">
      <h5>Lorem ipsum dolor sit amet</h5>
      <small class="news-date">
        <strong>26 avril 2016</strong>
      </small>
      <p>
        Respondent extrema primis, media utrisque, omnia omnibus. Non igitur bene. Negabat igitur ullam esse artem, quae ipsa a se proficisceretur; At iam decimum annum in spelunca iacet. Duo Reges: constructio interrete. Honesta oratio, Socratica, Platonis etiam.
      </p>
    </div>
  </div>
</div>
