---
title: pagination
name: pagination
collection: molecules
notes: |
  ##### Usage : `pagination`
---
<nav>
  <ul class="pagination">
    <li class="disabled">
      <a href="#" aria-label="Précédent">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    <li class="active"><a href="#">1</a></li>
    <li><a href="#">2</a></li>
    <li><a href="#">3</a></li>
    <li><a href="#">4</a></li>
    <li><a href="#">5</a></li>
    <li>
      <a href="#" aria-label="Suivant">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>
</nav>
