---
title: tocnav
name: tocnav
collection: molecules
notes: |
  ##### Usage : `tocnav`
---
<div class="tocnav">
  <ul class="list-unstyled">
    <li class="toc-item-h1"><a href="#" >Title 1</a></li>
    <li class="toc-item-h2"><a href="#" >Title 2</a></li>
    <li class="toc-item-h3"><a href="#" >Title 3</a></li>
    <li class="toc-item-h4"><a href="#" >Title 4</a></li>
    <li class="toc-item-h5"><a href="#" >Title 5</a></li>
    <li class="toc-item-h6"><a href="#" >Title 6</a></li>
  </ul>
</div>
